#!/bin/bash
# install.sh - use ONLY an external USB Bluetooth dongle on Linux
#
#   1. Disable the laptop's built-in Bluetooth chip (udev, survives reboot)
#   2. Enable Bluetooth Low Energy: ControllerMode = dual in BlueZ
#   3. Retire old "btmgmt le on" udev hacks that race with bluetoothd
#
# Usage:
#   sudo ./install.sh                     auto-detect the built-in chip
#   sudo ./install.sh --internal VID:PID      pick the chip yourself
#   sudo ./install.sh --dry-run           only show what would happen
#   sudo ./install.sh --yes               do not ask for confirmation
#
# Everything is backed up. Undo with: sudo ./uninstall.sh
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
CONF=/etc/bt-dongle-fix.conf
RULE=/etc/udev/rules.d/99-disable-internal-bt.rules
MAIN=/etc/bluetooth/main.conf
BACKUP_ROOT=/var/backups/bt-dongle-fix

DRY=0; YES=0; WANT=""
while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run)  DRY=1 ;;
        --yes|-y)   YES=1 ;;
        --internal) WANT="${2:-}"; shift ;;
        -h|--help)  sed -n '2,15p' "$0"; exit 0 ;;
        *) echo "Unknown option: $1 (see --help)"; exit 1 ;;
    esac
    shift
done

[ "$DRY" -eq 1 ] || [ "$(id -u)" -eq 0 ] || { echo "Run with sudo."; exit 1; }

# --- helpers -------------------------------------------------------------
attr() { cat "$1/$2" 2>/dev/null || true; }

# A USB device is Bluetooth if its device class is e0 (Wireless) or one of
# its interfaces is e0/01/01 (Bluetooth HCI). The device class is still
# readable when the chip is already de-authorized (no interfaces then).
is_bt() {
    local d=$1 i
    [ "$(attr "$d" bDeviceClass)" = "e0" ] && return 0
    for i in "$d":*; do
        [ "$(attr "$i" bInterfaceClass)$(attr "$i" bInterfaceSubClass)$(attr "$i" bInterfaceProtocol)" = "e00101" ] && return 0
    done
    return 1
}

usb_devices() {
    local d
    for d in /sys/bus/usb/devices/[0-9]*-[0-9]*; do
        case "$d" in *:*) continue ;; esac
        [ -e "$d/idVendor" ] && echo "$d"
    done
}

describe() {
    local d=$1
    printf '  %-6s %s:%s  %-10s %s\n' "$(basename "$d")" "$(attr "$d" idVendor)" \
        "$(attr "$d" idProduct)" "$(attr "$d" removable)" "$(attr "$d" product)"
}

# --- 1. find Bluetooth devices -------------------------------------------
INTERNAL=(); EXTERNAL=(); ALL=()
while read -r d; do
    is_bt "$d" || continue
    ALL+=("$d")
    id="$(attr "$d" idVendor):$(attr "$d" idProduct)"
    rem="$(attr "$d" removable)"
    if [ -n "$WANT" ]; then
        if [ "$id" = "$WANT" ] && [ "$rem" != "removable" ]; then INTERNAL+=("$d")
        else EXTERNAL+=("$d"); fi
    else
        if [ "$rem" = "fixed" ]; then INTERNAL+=("$d")
        else EXTERNAL+=("$d"); fi
    fi
done < <(usb_devices)

echo "Bluetooth USB devices found (port, VID:PID, removable, name):"
if [ ${#ALL[@]} -eq 0 ]; then echo "  (none)"; else for d in "${ALL[@]}"; do describe "$d"; done; fi
echo

if [ ${#INTERNAL[@]} -eq 0 ]; then
    echo "No built-in Bluetooth chip detected."
    if [ -n "$WANT" ]; then
        echo "  $WANT is not present, or it is plugged into an external port."
    else
        echo "  Built-in chips normally show 'fixed'. If yours shows 'unknown',"
        echo "  pick it yourself:  sudo $0 --internal VID:PID"
    fi
    exit 1
fi

echo "Will DISABLE (built-in):"
for d in "${INTERNAL[@]}"; do describe "$d"; done
echo "Will KEEP (external):"
if [ ${#EXTERNAL[@]} -eq 0 ]; then
    echo "  (none plugged in!)"
    echo
    echo "WARNING: no external dongle is plugged in right now. After this you"
    echo "will have no Bluetooth until you plug one in."
else
    for d in "${EXTERNAL[@]}"; do describe "$d"; done
fi
echo

# --- build the udev rule -------------------------------------------------
# Match on "removable==fixed" when the kernel knows the port is internal
# (a plugged-in dongle can never match). Otherwise fall back to the exact
# internal port name, which a dongle can never occupy either.
RULE_TEXT="# Generated by bt-dongle-fix install.sh - disables built-in Bluetooth.
# Writing 0 to 'authorized' makes the kernel de-configure the USB device:
# btusb is never bound and no hciX is created. It still shows in lsusb.
# Temporary on/off: sudo btinternal on|off   Remove: sudo ./uninstall.sh"
ENTRIES=""
for d in "${INTERNAL[@]}"; do
    v=$(attr "$d" idVendor); p=$(attr "$d" idProduct); port=$(basename "$d")
    if [ "$(attr "$d" removable)" = "fixed" ]; then
        match="ATTR{removable}==\"fixed\""
    else
        match="KERNEL==\"$port\""
    fi
    RULE_TEXT+=$'\n'"ACTION==\"add\", SUBSYSTEM==\"usb\", ATTR{idVendor}==\"$v\", ATTR{idProduct}==\"$p\", $match, ATTR{authorized}=\"0\""
    ENTRIES+="$v:$p:$port "
done

if [ "$DRY" -eq 1 ]; then
    echo "--- $RULE (dry run, not written) ---"
    echo "$RULE_TEXT"
    echo "--- $MAIN ---"
    echo "ControllerMode = dual"
    exit 0
fi

if [ "$YES" -eq 0 ]; then
    read -r -p "Continue? [y/N] " ans
    case "$ans" in y|Y|yes) ;; *) echo "Aborted."; exit 1 ;; esac
fi

# --- 2. backup -----------------------------------------------------------
TS=$(date +%Y%m%d-%H%M%S)
BK="$BACKUP_ROOT/$TS"
mkdir -p "$BK"
[ -f "$MAIN" ] && cp -a "$MAIN" "$BK/main.conf"
[ -f "$RULE" ] && cp -a "$RULE" "$BK/"
echo "[1/5] Backup: $BK"

# --- 3. disable the built-in chip ----------------------------------------
echo "$RULE_TEXT" > "$RULE"
chmod 0644 "$RULE"
install -m 0755 "$HERE/bin/btinternal" /usr/local/bin/btinternal
install -m 0755 "$HERE/bin/btpairing"  /usr/local/bin/btpairing
cat > "$CONF" <<EOF
# bt-dongle-fix state (used by btinternal and uninstall.sh)
INTERNAL="${ENTRIES% }"
BACKUP_DIR="$BK"
EOF
echo "[2/5] udev rule + 'btinternal' and 'btpairing' commands installed."

# --- 4. BlueZ: dual mode (BR/EDR + LE) -----------------------------------
if [ ! -f "$MAIN" ]; then
    mkdir -p "$(dirname "$MAIN")"
    printf '[General]\nControllerMode = dual\n' > "$MAIN"
elif grep -qE '^\s*ControllerMode\s*=' "$MAIN"; then
    sed -i -E 's/^\s*ControllerMode\s*=.*/ControllerMode = dual/' "$MAIN"
elif grep -q '^\[General\]' "$MAIN"; then
    sed -i '0,/^\[General\]/s//[General]\nControllerMode = dual/' "$MAIN"
else
    printf '\n[General]\nControllerMode = dual\n' >> "$MAIN"
fi
echo "[3/5] $MAIN: ControllerMode = dual (Low Energy on)."

# --- 5. retire udev hacks that run btmgmt/hciconfig ----------------------
retired=0
for f in /etc/udev/rules.d/*.rules; do
    [ -f "$f" ] && [ "$f" != "$RULE" ] || continue
    grep -qE 'RUN\+?=.*(btmgmt|hciconfig|enable-ble)' "$f" || continue
    cp -a "$f" "$BK/"
    mv "$f" "$f.disabled"
    echo "      retired: $f -> $(basename "$f").disabled"
    retired=1
done
[ "$retired" -eq 1 ] || echo "      no old btmgmt/hciconfig hacks found."
echo "[4/5] Old hacks checked."

# --- apply ---------------------------------------------------------------
udevadm control --reload-rules
udevadm trigger --action=add --subsystem-match=usb
sleep 2
systemctl restart bluetooth
sleep 3
echo "[5/5] udev reloaded, bluetooth restarted."
echo
/usr/local/bin/btinternal status || true
echo
echo "Undo everything: sudo $HERE/uninstall.sh"
